[package]
name = "url-fetcher"
version = "0.1.0"
authors = ["Ozan Sazak <ozan.sazak@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.35"
serde_json = "1.0"